### ISSUE TITLE
methodify doesn't work well for UPPERCASE ATTRIBUTES

### ISSUE THREAD

**Issue by joevandyk** [Jetbuilt/acumatica#1]
We have attributes with names like "ITEM CODE" -- the methodify method turns that into "i_te_m _co_de"

**Comment by jaredmoody** [comment]
I've addressed this in #3 - I don't know if you're actively using the gem, but let me know if you need a gem patch version bump.

**Comment by jaredmoody** [comment]
Nevermind, just released 0.2.1
