### ISSUE TITLE
Thank you for the code!

### ISSUE THREAD

**Issue by salticus** [Jetbuilt/acumatica#21]
Thank you for this code!

My plans are to to fork it for internal use. 

Is there anything to be done here?

(My plans include separating out ActiveSupport code with the goal of separating concerns and making the "one thing" for this code retrieval of Acumatica objects. However that seems like a breaking change for anyone relying on this code.)

**Comment by jaredmoody** [comment]
Hi there, you're welcome to fork this code - I don't think anything should be stopping you; I think likely that this is as far as my company is going to take this code.

There's lots to be done as far as this code does not cover much of the Acumatica API, only the endpoints I needed are built.

ActiveSupport is mainly being used to make the API more ruby-like; to transform strings and hash keys from things like `AttributeID` to `attribute_id`.

I've opened up the Discussions feature on this repo - if you have further questions we can discuss there without opening issues.
